Vagrant.configure("2") do |config|
    # Конфігурація для Ubuntu
    config.vm.define "ubuntu" do |ubuntu|
      ubuntu.vm.box = "ubuntu/bionic64"
      ubuntu.vm.hostname = "lab4-ubuntu"
      ubuntu.vm.network "private_network", type: "dhcp"
      ubuntu.vm.provision "shell", path: "provision-linux.sh"
    end
  
    # Конфігурація для Windows
    config.vm.define "windows" do |windows|
      windows.vm.box = "peru/windows-10"
      windows.vm.hostname = "lab4-windows"
      windows.vm.network "private_network", type: "dhcp"
      windows.vm.provision "shell", path: "provision-windows.ps1"
    end
  
    # Конфігурація для MacOS
    config.vm.define "macos" do |macos|
      macos.vm.box = "roboxes/macos-catalina"
      macos.vm.hostname = "lab4-macos"
      macos.vm.network "private_network", type: "dhcp"
      macos.vm.provision "shell", path: "provision-mac.sh"
    end
  end
  