# Vagrantfile for setting up a Linux environment
Vagrant.configure("2") do |config|
  
    config.vm.box = "ubuntu/focal64" # Ubuntu 20.04 LTS
  
    config.vm.hostname = "lab6-vm"
  
    config.vm.network "forwarded_port", guest: 5000, host: 5000 
  
    config.vm.synced_folder "../", "/home/vagrant/Lab6" 
  
    config.vm.provision "shell", path: "provision-linux.sh"
  end
  